package lib;

public interface ICONSTANTS {
    int HEIGHT_POS = 0;
    int WIDTH_POS = 1;
    float LUMINANCE_THRESHOLD = 0.35F;
    int GROUPS_QUANTITY = 16;
    float APT_PERCENTAGE = 35F;//AQUI
    int MAX_CHROMOSOME_VALUE = 65535;
    int INITIAL_POPULATION_SIZE = 13;
    int CHROMOSOMES_BITS = 16;
    float MUTATION_PERCENTAGE = 0.05F;
    int BIT_MASK = 0x1;
    int COLOR_SIMILARITY = 5;//AQUI
    int TWO_PI_RADIAN = 360;
    int PETAL_QUANTITY = 5;
    int CENTER_PETAL_X = 250;
    int CENTER_PETAL_Y = 250;
    int POLYGON_WIDTH = 5;
    int POLYGON_HEIGHT = 10;
    int MAX_PETAL_WIDTH = 30;
    int MAX_PETAL_HEIGHT = 170;
    int CENTER_WIDTH = 10;
    int CENTER_HEIGHT = 15;
    int CENTER_QUANTITY = 5;
    int LINE_IN_PETAL = 15;
    int LINES_PER_PETAL = 12;
    int GENERATIONS_GROWTH = 3;
    int CANT_INDEX = 0;
    int PERCENTAGE_INDEX = 1;
    int POLYGON_PER_PETAL = 2*LINES_PER_PETAL*LINE_IN_PETAL;

}
