package lib;

public interface ICONSTANTS {
    int HEIGHT_POS = 0;
    int WIDTH_POS = 1;
    float LUMINANCE_THRESHOLD = 0.6F;
    int GROUPS_QUANTITY = 16;
    float COLOR_BASE = 441.6729559F;
    float PERCENTAGE_COLOR = 0.5F;
    float DISTRIBUTION_COLOR_PERCENTAGE=0.4F;
    float APT_PERCENTAGE = 0.2F;
    int MAX_CHROMOSOME_VALUE = 65535;
    int INITIAL_POPULATION_SIZE = 13;
    int CHROMOSOMES_BITS = 16;
    float MUTATION_PERCENTAGE = 0.05F;
    int MAX_POPULATION_SIZE = 100;
}
